/**
 * Monthly Attendance + Payroll reconciliation row builder (Excel Sheet 3).
 *
 * PURE — no I/O. It ONLY combines values that already come from the two
 * authoritative sources; it NEVER re-derives payroll amounts:
 *   • Attendance side  — buildRangeSummary / summarizeEmployee (present, half,
 *     incomplete, in-progress, absent, approved-leave days, effective & OT hours).
 *   • Payroll side     — the STORED payroll row (hr_hrpayrolls) generated by the
 *     payroll engine: gross, net, LOP, hour-shortage, PT, PF, income-tax, advance,
 *     OT pay, salary-working & payable days. Reading the stored row means the sheet
 *     reconciles with the Payroll UI / Payroll Register BY CONSTRUCTION.
 *
 * The only value not stored on the row is the hour-shortage HOUR count (the row
 * keeps the ₹ deduction, hr_hourdeduction); the caller supplies `shortageHours`
 * from the same monthly-balance service the payroll generation used.
 *
 * Salary Working Days = the payroll's own hr_workingdays (= att.workingDays, the
 * FULL working days it uses as the per-day divisor). Approved leave is salary
 * protected, so it is shown in its OWN column and NEVER subtracted here.
 */

const num = (v) => (Number.isFinite(Number(v)) ? Number(v) : 0);
const round2 = (v) => Math.round((num(v) + Number.EPSILON) * 100) / 100;

/**
 * "Other Deductions" = every stored deduction that is NOT LOP, NOT hour-shortage
 * and NOT Professional Tax: PF + Income Tax + Advance recovery + the "Other"
 * bucket. This is exactly what remains so that, for any generated row:
 *   PT + LOP Deduction + Shortage Deduction + Other Deductions === Gross − Net.
 * Returns null when there is no payroll row (nothing was generated to reconcile).
 */
function otherDeductionsOf(row) {
  if (!row) return null;
  return round2(num(row.hr_pf) + num(row.hr_incometax) + num(row.hr_advance) + num(row.hr_deductions));
}

/** LOP is day-based (absent working days) → its hour equivalent is lopDays × full-day hours. */
function lopHoursOf(lopDays, fullDayHours) {
  return round2(num(lopDays) * num(fullDayHours));
}

/**
 * Build ONE reconciliation row (raw numbers — the Excel layer formats ₹ / hours).
 * Money fields are null when the employee has no payroll row for the month, so the
 * sheet can render "—" instead of inventing a value.
 *
 * @param {object} p
 * @param {string} p.employeeId               display id (etimecode ?? guid)
 * @param {string} p.employeeName
 * @param {{calendar:number, working:number}} p.rc
 * @param {object} p.summary                  summarizeEmployee output
 * @param {number} p.approvedLeaveDays        approvedLeaveDaysWeighted (half-day aware)
 * @param {object|null} p.payrollRow          stored hr_hrpayrolls row, or null
 * @param {number} p.shortageHours            monthly-balance shortageHours (0 when none)
 * @param {number} p.fullDayHours             policy full-day expected hours (9)
 */
function buildReconRow({ employeeId, employeeName, rc, summary, approvedLeaveDays, payrollRow, shortageHours, fullDayHours }) {
  const pr = payrollRow || null;
  const s = summary || {};
  // LOP days = the payroll's absent (LOP) days when a row exists; else the
  // authoritative attendance absent count (so LOP Hours still shows pre-generation).
  const lopDays = pr ? num(pr.hr_absentdays) : num(s.absent);
  return {
    // 1–11 attendance / day counts
    employeeId,
    employeeName,
    calendarDays: num(rc.calendar),
    workingDays: num(rc.working),
    presentDays: num(s.present),
    approvedLeaveDays: round2(approvedLeaveDays),
    absentDays: num(s.absent),
    halfDays: num(s.half),
    incompleteDays: num(s.incomplete),
    inProgressDays: num(s.inProgress),
    // Salary Working Days = payroll's full working days (approved leave NOT subtracted).
    salaryWorkingDays: pr ? num(pr.hr_workingdays) : num(rc.working),
    // 12–13 hours / LOP
    effectiveHours: round2(s.effectiveHours),
    lopHours: lopHoursOf(lopDays, fullDayHours),
    lopDeduction: pr ? num(pr.hr_lop) : null,
    // 15–16 shortage (kept SEPARATE from LOP)
    shortageHours: round2(shortageHours),
    shortageDeduction: pr ? num(pr.hr_hourdeduction) : null,
    // 17–19 other money
    professionalTax: pr ? num(pr.hr_professionaltax) : null,
    otherDeductions: otherDeductionsOf(pr),
    grossPay: pr ? num(pr.hr_gross) : null,
    // 20–22 OT + net
    otHours: round2(s.overtimeHours),
    otPay: pr ? num(pr.hr_overtime) : null,       // already respects "Calculate OT Pay" (baked at generation)
    netPay: pr ? num(pr.hr_netpay) : null,
    hasPayroll: !!pr,
  };
}

module.exports = { buildReconRow, otherDeductionsOf, lopHoursOf };
